### ISSUE TITLE
debian12bookworm on Arm64 with Zoneminder 1.37.55* doesn't complete apt-get install zoneminder command

### ISSUE THREAD

**Issue by xenek** [connortechnology/ZoneMinder#113]
{} version 1.37.55 (development version?)
{} installed ZoneMinder using apt-get install zoneminder
{} name and version of OS https://dietpi.com/downloads/images/DietPi_PINEA64-ARMv8-Bookworm.img.xz
- Browser name and version (if this is an issue with the web interface) NOT APPLICABLE 

**Describe the bug**

1. using root
2. skipping adding secondary user
3. copying script at https://wiki.zoneminder.com/Debian_12_Bookworm_with_Zoneminder_1.36.33#Debian_12_with_Zoneminder_1.37.x 
4. updating permission & execute script
5. during script running, error messages occur
6. when visiting http://(ipaddressofhost) apache shows successful installation
7. when visiting http://(ipaddressofhost)/zm all you get is a blank screen (no text, no gfx, no error, nothing except a blank)

Summary:  didn't work, installer on arm64 crashed out under Debian Bookworm, so web gui didn't show anything
Terminal log follows below.

**To Reproduce**
1. Do what I did above on a Arm64 device or any h/w using debian12 (bookwork)/zm 1.37.x
2. Perhaps it fails similarly 
3. I did begin the installation of zm1.36.x cause I can't read instructions & I'm bad at linuz so maybe I broke it?
4. But I think the install script APT uses has a bug in somewhere...

**Expected behavior**
When visiting http://(ipaddressofhost)/zm I expected the web gui to allow me to continue setup

**Debug Logs**
```
Do you want to continue? [Y/n] y
Setting up zoneminder (1.37.55~20240301.24-bookworm) ...
detected systemd
Detected db service is mariadb.service
Checking for db
Db exists.
Updating permissions for user zmuser@localhost
Please give a valid option
Usage:
    zmupdate.pl -c,--check | -f,--freshen | -v<version>,--version=<version>
    [-u <dbuser> -p <dbpass>]

Options:
     -c, --check                       - Check for updated versions of ZoneMinder.
                                         If not interactive zmupdate.pl will stay running, checking every hour.
                                         If interactive will try once, print out result and quit.
     -f, --freshen                     - Freshen the configuration in the database. Equivalent of old zmconfig.pl -noi
     --migrate-events                  - Update database structures as per USE_DEEP_STORAGE setting.
     -v <version>, --version=<version> - Force upgrade to the current version from <version>
     -u <dbuser>, --user=<dbuser>      - Alternate DB user with privileges to alter DB
     -p <dbpass>, --pass=<dbpass>      - Password of alternate DB user with privileges to alter DB
     -s, --super                       - Use system maintenance account on debian based systems instead of unprivileged account
     -d <dir>, --dir=<dir>             - Directory containing update files if not in default build location
     -interactive                      - interact with the user
     -nointeractive                    - do not interact with the user

Error updating db.
dpkg: error processing package zoneminder (--configure):
 installed zoneminder package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 zoneminder
```

RESOLUTION: (yes, I resolved this, don't know how, but one of these things below did it, found at https://forums.zoneminder.com/viewtopic.php?t=32558 that linked to https://zoneminder.readthedocs.io/en/latest/installationguide/debian.html#debian-11-bullseye )

```
Switch into root user and create database and database user

sudo su
mariadb
CREATE DATABASE zm;
CREATE USER zmuser@localhost IDENTIFIED BY 'zmpass';
GRANT ALL ON zm.* TO zmuser@localhost;
FLUSH PRIVILEGES;
exit;
exit

```

But.. I think it was this command that fixed it

```


zmupdate.pl -f


```

Do a sudo reboot now 
afterward, now I get web console.

~end

**Comment by connortechnology** [comment]
I actually suspect you have an older version of zm installed... which is weird that the new one didn't overwrite the old..

Anyways, I'm closing as there is nothing we can do to fix this mess.  wiki needs an auditing.
