### ISSUE TITLE
Montage review timeline does not reorder on resize (captions do)

### ISSUE THREAD

**Issue by MalakymR** [connortechnology/ZoneMinder#23]
zm 1.31.6 storageareas

Under montage review, when resizing a view, the timeline captions reorder - but the timeline itself doesn't.

To demonstrate this I record with 2 cameras. Stop one for a short period of time before restarting it, this shows a clear gap in the timeline so we know which camera is which. Go to montage review and show the last hour. Resize camera 2 and the caption for camera 2 moves up, but the timeline itself does not change - so the captions are now on the wrong timeline.

This had occured in a few versions prior, including zoneminder/zoneminder 1.31.4.

Occurs in Firefox 56, 57, Chrome 59, Vivaldi 1.11 and IE11

![zonemindermontageview-1 31 6](https://user-images.githubusercontent.com/7790536/31176432-b6c704ea-a90a-11e7-8a57-83b7f3383261.jpg)

**Comment by MalakymR** [comment]
Is there a reason why the order of these timelines need to change? I can't think of a reason to do so, could simplify it otherwise.

**Comment by connortechnology** [comment]
Agreed, I see no reason.

**Comment by digital-gnome** [comment]
line 554 `  monitorPtr.sort(compSize);`
It sorts the monitor array to change positions when they are resized.  This order isn't used for generating the graphs, just the captions.  Removing this line means the captions stay lined up but the monitor displays aren't sorted either.  It's possible to copy the array and restore it after the displays are resized but then the monitor images don't match the graph.  I don't see any particular reason for the monitors to re-order at all.

Web Colour under the Misc tab in monitor source will change the colors of the graphs.  Makes it easier to tell what's going on.

**Comment by MalakymR** [comment]
Even if someone thinks the graphs should be reordered, it'd probably be better to remove that line until the work to do so is complete.

**Comment by MalakymR** [comment]
Fixed by merge.
