### ISSUE TITLE
storageareas 1.31.9 - montage review group "all" executes an empty WHERE clause.

### ISSUE THREAD

**Issue by MalakymR** [connortechnology/ZoneMinder#39]
This page works fine when a group is selected, except "ALL" where the SQL statement is including WHERE when its not required.

`web_php[3274]: FAT [SQL-ERR dbFetchAll no result, statement was 'SELECT * FROM Monitors WHERE  ORDER BY Sequence ASC']`

**Comment by connortechnology** [comment]
Can you please test latest code.

**Comment by MalakymR** [comment]
This is fixed - I had installed a fresh copy yesterday and there was no problem, so it was due to the day before that or an update quirk.
