### ISSUE TITLE
ERR - Can't insert event

### ISSUE THREAD

**Issue by shaun-ba** [connortechnology/ZoneMinder#78]
Another issue I've run into now with recording in Modect, can't insert events on 1.31.26

```
Can't insert event: Data truncated for column 'Scheme' at row 1. sql was (INSERT INTO Events ( MonitorId, StorageId, Name, StartTime, Width, Height, Cause, Notes, StateId, Orientation, Videoed, DefaultVideo, SaveJPEGs, Scheme ) values ( 1, 0, 'New Event', from_unixtime( 1516694165 ), 1920, 1080, 'Motion', 'Motion: All', 1, 1, 0, '', 0, '' ))
```

**Comment by connortechnology** [comment]
I've pushed a new version which should fix it.  Please let me know.

**Comment by shaun-ba** [comment]
Yes, this is now resolved

**Comment by shaun-ba** [comment]
fixed!

**Comment by connortechnology** [comment]
You need to re-run update 17.
mysql -u zmuser -p zm < /usr/share/zoneminder/db/zm_update-1.31.17.sql

**Comment by shaun-ba** [comment]
Works, but shouldn't this also check/update the DB in all subsequent versions?
