### ISSUE TITLE
Zoneminder background process leaking logs to foreground.

### ISSUE THREAD

**Issue by shaun-ba** [connortechnology/ZoneMinder#87]
Zoneminder background process leaking logs to foreground.

Replicate: Login to server, wait a few seconds and start seeing logs spammed to foreground.

```
n@zm-vid:~$ 
Broadcast message from systemd-journald@zm-vid (Mon 2018-03-12 15:41:51 UTC):

zma_m11[539]:  [zma_m11] [Rear-sub: 6255000 - Analysing at 5.99 fps]


Broadcast message from systemd-journald@zm-vid (Mon 2018-03-12 15:41:52 UTC):

zma_m8[503]:  [zma_m8] [Front-sub: 6255000 - Analysing at 6.02 fps]
```

**Comment by pliablepixels** [comment]
@connortechnology - the fixes did not solve this problem - its gotten worse (more frequent)

**Comment by shaun-ba** [comment]
server is unusable :D

**Comment by connortechnology** [comment]
weird. Anyways, turn off logging to syslog.  Or set it to critical instead of info..

**Comment by shaun-ba** [comment]
Ok, that's a temporary workaround whilst you investigate and fix it?

**Comment by pliablepixels** [comment]
My current workaround is to add `ForwardToWall=no` to `/etc/systemd/journald.conf` and restart the service - this kills the broadcast messages for all apps including ZM, but really is a temporary workaround. There is something ZM-SA is doing that is triggering this that no other app is doing.

**Comment by shaun-ba** [comment]
@pliablepixels I've not come across this with ANY software in the past, very odd!

**Comment by connortechnology** [comment]
So what seems to be happening is that when the process is told to rotate logs, it starts doing this.  So something is wrong in the log reload functions.  

Should have a fix soon.

**Comment by connortechnology** [comment]
I think I found it.

Please note that the behaviour only happens after a reload, so to test, all you have do is
killall -HUP zma

**Comment by pliablepixels** [comment]
so far so good

Updated: seems resolved for me.

**Comment by shaun-ba** [comment]
resolved!
