### ISSUE TITLE
Unable to open input <> due to: Operation now in progress

### ISSUE THREAD

**Issue by shaun-ba** [connortechnology/ZoneMinder#99]
Upgraded to 1.31.44 and now getting this on all monitors.

Get this on the frontend when trying to watch stream:

```
http://domain.com/zm/cgi-bin/nph-zms?scale=100&width=1920px&height=1080px&mode=jpeg&maxfps=30&buffer=1000&monitor=1&auth=2e82a210090b4f0653f030&connkey=36785&rand=1525785938
Request Method: GET
Status Code: 404 Not Found
```

**Comment by connortechnology** [comment]
This sounds like two different issues.  The Unable to open input... is there actually something in between the <>'s?  What type of monitors?  Sounds like ffmpeg.  

The second 404 bit sounds like a broken apache config in terms of the CGI ScriptAlias

Please see https://gist.github.com/connortechnology/9ca83f812d94b2777b93ad54ee45067e for example apache config.

**Comment by shaun-ba** [comment]
Yes there is a monitor in here and it was ffmpeg.

I had used the apache config from this gist already!
